osx_image: xcode9
language: objective-c
xcode_project: ObjC-IOS.xcodeproj
xcode_scheme: ObjC-IOS
before_script:
- sudo apt-get install jq
- ./scripts/add-key.sh
- ./scripts/update-bundle.sh
- ./scripts/sign-and-upload.sh
script:
- xcodebuild clean build -project ObjC-IOS.xcodeproj -scheme ObjC-IOS -sdk iphoneos
  -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO
after_script:
- ./scripts/remove-key.sh
after_success:
- ./scripts/testflight.sh

env:
  global:
  - APP_NAME="ObjC-IOS"
  - DEVELOPER_NAME="Pfizer International Inc"
  - INFO_PLIST="ObjC-IOS/Info.plist"
  - PROFILE_NAME="TCS_Distribution_Profile_16To17"
  - secure: NhN2e2nLLbwU8XSBKf3Bs6I7LQTkzWwsqCcoiRd6LdTrL3861keZSHePnFNa9U+9GNVq+bTrUSkZ9Xw+nIRQNfP++uVn4y6E4EgmJWEMY7swz8ZwEtdlZkehK/rPofQrBH4yZr3Vgp9+Mi8SHFe5UHHWCZZS3VISTzIVqWgp4HLb/0cPE65cbmGTjKuJYdEcDR5UUBH5lOENd3GKSmTsiYdpXwc/TW0CrM7NkhvPLu5GoWEcMxOi80R21cGeZ2XpglLjj1DVwxfHqbdVK7QOY+HQRIDvm5+V/3TfNpHcpnz0RA22Hev/5OgwulC7/igiWSkQEr+5YAalyW55xtWk5vgjOnZrkp2o7rakaUohpq4V+drrzCBXgfjqP9HDI2QaX44OYvlAH6Yj/XH8gb4ilGH739WJjcTL58qGGB7xRT19etYREriB17GpV5xah4bGI9nsXz44pAx9Mbba90P7ktTgQFBthD4CrR7zK6eiOTHFDUiIMykiAnG7EenWHRbFmXswTp2I47cmXeXCk8MJ1zhILhg4b6C3CEvQ41F5U5g3JXpIge4MHHw4FxS8nGD2Zs7uthhP8Q4rMKqMu4DUoTabZRvV1F1Ta1gEMAM5cvtmHdNixChLGmkUJ2zJZcwdoZjduFWmOtSsyh7A93YT1VNRhp0ZHImnFM6OjuWgWFM=
  - secure: luFjkpwQGZ9QCtktcW7wm2cviIxr/vsakzL8Ayybk5qOLg6yA7Z/HxEQV/a36UY9GEAxFazB45ksAVrLhoXHTosAHMVim3LgRtA2u7u0EAS0kYS8l7BSxw9zRLH5cJENyEh5UprGczfBY4f9iUP+5jgjMUOEfV0QPiWdbPQbysMlrvMfLiEVqH3W/+GSOpA7qGcNglcFiiGQURv5BjKlOnyQuo2PZpFsTP3t2XyDeyD4sFhv2b99gx26LbnKleo3C1G/jHa7Efmfwr9VPKSoSLeh1o22THc1P+gQijvWk3747zLtwmtVCSzkCyV1jWVcx/UDRGKcgyJcf6CTypU21KDP+fbJWYQcwvzOw3Cade/2tKCTqkts1z7ft4iDyGCDSvx2UgvQkTjxUuNGN3oX3Ird5uBVK+T4igjT1YB3Mz0StGwuL5vn+1VGhrplduQ+k0NzTN86/DmrQ0HTDWaLrf5sAjJiWGeStMrARfTTouXKncGOUQtRjQFeL6kStRC12K51SJDkSA6dUJW6lZX9ogRxPfpsyD9rmFphsH13IWsBs560tQjz/FFp5bNYjlpKV3zzs3YU+xpEOyDSWxVZyPLnRwVDW7ToGckyk/7bPiFfR7rSS/vx2lJtqvq9YbOh98dk8wRciJu9I7I3XUZ4iyJAwxFe1FHM3f6KdI/G6xI=
  - secure: aOa5uAIBgczT4p+cSgMlhX+Ia7lHS9h1t2zWvcRk0tHi3vX/xjDG8cEP46DRaOzVMkb/FvQp6h6SkvBGe01n2Cu6RM51pTZPkqBy1A+zN+xh2RmP94DQTI1aF00EguMRKwoZDE4W5s+Oiw8UQKVKPD0A0cqy2FzdGtXABS/UHEDY3Y3VKZKZFNHW2hFRcT4AwbCAGtvUyv2vjQDW33odHdQbAdXTAEtziTR2wIEAp2wnHDQcbY7pGw2NFx1FzxlYszUEacWrSYhURzvRn4sVRvBISRZ37lKs5cExwGb7ccyQk+pJB042vpssT7Dx9PjwO6iV2/M9mBiDUS1aqTGwR9TyYBA9bOhISC07kFxY5NhaftzPeqq9bZJGt5DKvA2Py5S4ASnEX3N0DZdEDo9F5oa6JkSXe7TaKRnSD3ZtcFjChdaIe2BpV29GDlHzmsRBWfU5GXT6h9sP4Af/PHPa2TuQ7qVeUv/rqXPClQI+G1EPqKj1yvZZNYukopyZlTbQ3eUoYeuQdUN3iBRepVaWkO6KiVPNFsDe8wVW7Apt4NGjwIlQhfOHI77JR0PxmJ1ANcmjia8fI9HSmwhrmNpC3EEBQMUFuXlj9tbgfIlqqVkm98UcHFFatssRHJHldYLmPPcCig6mgTmPQ0H60KrKvGez0btuJcZQm/aX5G+p8To=
